[programs.devnet]
tasks = "EJuRXDLaqc2bVrqPwq4WPwXDEiXyatomKzN6g8zgo2Th"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/swaroopmaddu/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
